/* Automated test driver for Lab 04. DO NOT EDIT THIS FILE. */
public class Lab04StringToolkitTest {

    public static void main(String[] args) {

        String out1 = TestRunner.runMain(Lab04StringToolkit::main, "0 0 3 4\nLamar2026\n");
        TestRunner.section("Case 1 - points (0,0)-(3,4) and the word Lamar2026");
        TestRunner.checkOutputContains("Distance printed to 2 decimals", out1, "Distance: 5.00");
        TestRunner.checkOutputContains("Rounded distance", out1, "Rounded distance: 5");
        TestRunner.checkOutputContains("Length", out1, "Length: 9");
        TestRunner.checkOutputContains("First character", out1, "First character: L");
        TestRunner.checkOutputContains("Last character", out1, "Last character: 6");
        TestRunner.checkOutputContains("Last is a digit", out1, "Last is a digit: true");
        TestRunner.checkOutputContains("Uppercase conversion", out1, "Uppercase: LAMAR2026");
        TestRunner.checkOutputContains("First five characters", out1, "First five: Lamar");
        TestRunner.checkOutputContains("Index of a", out1, "Index of a: 1");

        String out2 = TestRunner.runMain(Lab04StringToolkit::main, "2 3 8 11\nCardinalPride\n");
        TestRunner.section("Case 2 - points (2,3)-(8,11) and the word CardinalPride");
        TestRunner.checkOutputContains("Distance = 10.00", out2, "Distance: 10.00");
        TestRunner.checkOutputContains("Rounded distance", out2, "Rounded distance: 10");
        TestRunner.checkOutputContains("Length", out2, "Length: 13");
        TestRunner.checkOutputContains("First character", out2, "First character: C");
        TestRunner.checkOutputContains("Last character", out2, "Last character: e");
        TestRunner.checkOutputContains("Last is not a digit", out2, "Last is a digit: false");
        TestRunner.checkOutputContains("Uppercase conversion", out2, "Uppercase: CARDINALPRIDE");
        TestRunner.checkOutputContains("First five characters", out2, "First five: Cardi");
        TestRunner.checkOutputContains("Index of a", out2, "Index of a: 1");

        String out3 = TestRunner.runMain(Lab04StringToolkit::main, "-1.5 -2 2.5 1\nSTAMPEDE3\n");
        TestRunner.section("Case 3 - negative coordinates and an all-caps word");
        TestRunner.checkOutputContains("Distance = 5.00", out3, "Distance: 5.00");
        TestRunner.checkOutputContains("Length", out3, "Length: 9");
        TestRunner.checkOutputContains("Last is a digit", out3, "Last is a digit: true");
        TestRunner.checkOutputContains("First five characters", out3, "First five: STAMP");
        TestRunner.checkOutputContains("Lowercase a is absent, indexOf returns -1", out3, "Index of a: -1");

        TestRunner.exitWithSummary();
    }
}
